spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/midas-admin
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

server:
  port: 8080

halo:
  swagger:
    enabled: true
    api:
      title: midas-admin
      name: midas-admin
      description: midas-admin管控端
      version: 1.0.0
      contactName: xx.xx
      contactEmail: xx.xx@itxh.net

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/
  instance:
    prefer-ip-address: true

